2019-09-06 10:23:05,269 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:45]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-06 10:23:05,334 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:45]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-06 10:23:45,094 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-06 10:23:45,094 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-06 10:25:43,764 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-06 10:25:43,764 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-06 10:43:17,405 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-06 10:43:17,405 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-06 10:44:04,978 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-06 10:44:04,978 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-06 10:53:00,567 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-06 10:53:00,567 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-06 10:58:07,415 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-06 10:58:07,415 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-06 11:05:40,360 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-06 11:05:40,360 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-06 11:17:19,220 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-06 11:17:19,220 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-06 11:35:43,029 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-06 11:35:43,029 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-06 12:05:50,646 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-06 12:05:50,646 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-06 12:08:57,366 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-06 12:08:57,366 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-06 12:38:03,009 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-06 12:38:03,009 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-06 13:15:53,892 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-06 13:15:53,892 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-06 13:33:34,642 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-06 13:33:34,642 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-06 13:34:27,127 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-06 13:34:27,127 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-06 13:43:07,069 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-06 13:43:07,069 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-06 13:54:49,794 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-06 13:54:49,795 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-06 13:57:44,801 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-06 13:57:44,801 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-06 14:08:47,986 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-06 14:08:47,986 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-06 17:52:49,840 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-06 17:52:56,480 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-06 17:52:56,480 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-06 17:52:56,557 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-06 17:52:56,557 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-06 17:52:56,557 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-06 17:52:56,626 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-06 17:52:56,626 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-06 17:52:56,627 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-06 17:52:57,770 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-06 17:52:57,770 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-06 17:52:57,770 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-06 17:52:58,913 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-06 17:52:58,913 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-06 17:52:58,913 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-06 17:53:00,050 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-06 17:53:00,050 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-06 17:53:00,050 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-06 17:53:01,190 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-06 17:53:01,190 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-06 17:53:01,190 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-06 17:55:08,402 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-06 17:55:13,905 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-06 17:55:13,905 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-06 17:55:13,984 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-06 17:55:13,984 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-06 17:55:13,984 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-06 17:55:15,147 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-06 17:55:15,148 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-06 17:55:15,148 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-06 17:55:16,285 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-06 17:55:16,285 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-06 17:55:16,285 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-06 17:55:17,457 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-06 17:55:17,457 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-06 17:55:17,457 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-06 17:55:18,623 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-06 17:55:18,623 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-06 17:55:18,623 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-06 17:55:32,044 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-06 17:55:32,219 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-06 17:55:32,219 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-06 17:55:32,376 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-06 17:55:32,376 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-06 17:55:32,377 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-06 17:56:48,473 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-06 17:56:48,549 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-06 17:56:48,549 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-06 17:56:48,619 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-06 17:56:48,619 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-06 17:56:48,619 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-06 18:00:56,048 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-06 18:00:56,048 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-06 18:00:57,146 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/common/cmp_res_req.py] [verify_is_pass ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/common/cmp_res_req.py:59]- 测试用例预期结果与实际结果对比方法出现异常，异常原因：Expecting value: line 1 column 1 (char 0)
2019-09-06 18:03:53,880 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-06 18:03:53,960 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-06 18:03:53,960 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-06 18:03:54,033 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-06 18:03:54,033 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-06 18:03:54,033 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-06 18:03:55,129 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/common/cmp_res_req.py] [verify_is_pass ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/common/cmp_res_req.py:59]- 测试用例预期结果与实际结果对比方法出现异常，异常原因：Expecting value: line 1 column 1 (char 0)
2019-09-06 18:07:35,259 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-06 18:07:35,339 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-06 18:07:35,340 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-06 18:07:49,913 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-06 18:07:49,988 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-06 18:07:49,988 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-06 18:07:50,057 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-06 18:07:50,057 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-06 18:07:50,057 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-06 18:07:51,158 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/common/cmp_res_req.py] [verify_is_pass ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/common/cmp_res_req.py:59]- 测试用例预期结果与实际结果对比方法出现异常，异常原因：Expecting value: line 1 column 1 (char 0)
2019-09-06 18:08:36,307 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-06 18:08:36,470 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-06 18:08:36,471 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-06 18:08:36,628 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-06 18:08:36,628 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-06 18:08:36,629 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-06 18:09:58,319 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-06 18:09:58,402 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-06 18:09:58,403 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-06 18:09:58,480 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-06 18:09:58,480 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-06 18:09:58,480 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-06 18:11:42,276 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-06 18:11:42,445 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-06 18:11:42,445 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-06 18:11:42,603 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-06 18:11:42,604 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-06 18:11:42,605 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-06 18:11:50,000 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-06 18:11:50,175 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-06 18:11:50,176 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-06 18:11:50,338 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-06 18:11:50,338 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-06 18:11:50,339 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-06 18:12:09,377 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-06 18:12:09,463 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-06 18:12:09,463 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-06 18:12:09,536 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-06 18:12:09,537 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-06 18:12:09,537 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-06 18:12:15,340 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-06 18:12:15,509 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-06 18:12:15,510 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-06 18:12:15,670 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-06 18:12:15,670 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-06 18:12:15,671 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-06 18:12:27,105 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-06 18:12:27,270 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-06 18:12:27,270 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-06 18:12:27,427 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-06 18:12:27,427 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-06 18:12:27,428 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-06 18:12:30,734 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-06 18:12:30,897 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-06 18:12:30,897 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-06 18:12:31,056 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-06 18:12:31,056 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-06 18:12:31,057 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-06 18:13:29,215 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-06 18:13:29,510 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-06 18:13:29,511 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-06 18:13:29,707 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-06 18:13:29,707 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-06 18:13:29,709 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-06 18:15:19,884 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-06 18:15:20,065 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-06 18:15:20,066 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
2019-09-06 18:15:20,234 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-06 18:15:20,234 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：__init__() takes 1 positional argument but 3 were given
2019-09-06 18:15:20,236 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/param_global.py] [deal_param_name_tuple ][__file__:59]- 处理接口请求参数名出现异常，异常原因：list index out of range
