2019-09-03 11:55:49,499 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_sheet ][__file__:34]- 操作EXCEL表类获取sheet页内容异常，异常原因：[Errno 2] No such file or directory: ''
2019-09-03 11:55:49,499 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [__init__ ][__file__:16]- 操作EXCEL表类初始化异常，异常原因：'NoneType' object has no attribute 'nrows'
2019-09-03 11:55:49,499 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_row_col_list ][__file__:129]- 操作EXCEL表类获取值对应的行号出现异常，异常原因：'NoneType' object has no attribute 'nrows'
2019-09-03 11:55:49,499 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：'NoneType' object is not subscriptable
2019-09-03 11:55:49,500 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_sheet ][__file__:34]- 操作EXCEL表类获取sheet页内容异常，异常原因：[Errno 2] No such file or directory: ''
2019-09-03 11:55:49,500 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [__init__ ][__file__:16]- 操作EXCEL表类初始化异常，异常原因：'NoneType' object has no attribute 'nrows'
2019-09-03 11:55:49,500 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_row_col_list ][__file__:129]- 操作EXCEL表类获取值对应的行号出现异常，异常原因：'NoneType' object has no attribute 'nrows'
2019-09-03 11:55:49,500 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：'NoneType' object is not subscriptable
2019-09-03 12:02:25,988 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_sheet ][__file__:34]- 操作EXCEL表类获取sheet页内容异常，异常原因：[Errno 2] No such file or directory: ''
2019-09-03 12:02:25,988 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [__init__ ][__file__:16]- 操作EXCEL表类初始化异常，异常原因：'NoneType' object has no attribute 'nrows'
2019-09-03 12:02:25,988 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_row_col_list ][__file__:129]- 操作EXCEL表类获取值对应的行号出现异常，异常原因：'NoneType' object has no attribute 'nrows'
2019-09-03 12:02:25,988 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：'NoneType' object is not subscriptable
2019-09-03 12:02:25,988 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_sheet ][__file__:34]- 操作EXCEL表类获取sheet页内容异常，异常原因：[Errno 2] No such file or directory: ''
2019-09-03 12:02:25,988 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [__init__ ][__file__:16]- 操作EXCEL表类初始化异常，异常原因：'NoneType' object has no attribute 'nrows'
2019-09-03 12:02:25,988 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_row_col_list ][__file__:129]- 操作EXCEL表类获取值对应的行号出现异常，异常原因：'NoneType' object has no attribute 'nrows'
2019-09-03 12:02:25,988 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：'NoneType' object is not subscriptable
2019-09-03 12:02:49,222 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_sheet ][__file__:34]- 操作EXCEL表类获取sheet页内容异常，异常原因：[Errno 2] No such file or directory: ''
2019-09-03 12:02:49,222 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [__init__ ][__file__:16]- 操作EXCEL表类初始化异常，异常原因：'NoneType' object has no attribute 'nrows'
2019-09-03 12:02:49,222 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_row_col_list ][__file__:129]- 操作EXCEL表类获取值对应的行号出现异常，异常原因：'NoneType' object has no attribute 'nrows'
2019-09-03 12:02:49,223 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：'NoneType' object is not subscriptable
2019-09-03 12:02:49,223 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_sheet ][__file__:34]- 操作EXCEL表类获取sheet页内容异常，异常原因：[Errno 2] No such file or directory: ''
2019-09-03 12:02:49,223 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [__init__ ][__file__:16]- 操作EXCEL表类初始化异常，异常原因：'NoneType' object has no attribute 'nrows'
2019-09-03 12:02:49,223 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_row_col_list ][__file__:129]- 操作EXCEL表类获取值对应的行号出现异常，异常原因：'NoneType' object has no attribute 'nrows'
2019-09-03 12:02:49,223 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：'NoneType' object is not subscriptable
2019-09-03 12:03:16,266 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_sheet ][__file__:34]- 操作EXCEL表类获取sheet页内容异常，异常原因：[Errno 2] No such file or directory: ''
2019-09-03 12:03:16,267 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [__init__ ][__file__:16]- 操作EXCEL表类初始化异常，异常原因：'NoneType' object has no attribute 'nrows'
2019-09-03 12:03:16,267 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_row_col_list ][__file__:129]- 操作EXCEL表类获取值对应的行号出现异常，异常原因：'NoneType' object has no attribute 'nrows'
2019-09-03 12:03:16,267 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：'NoneType' object is not subscriptable
2019-09-03 12:03:16,267 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_sheet ][__file__:34]- 操作EXCEL表类获取sheet页内容异常，异常原因：[Errno 2] No such file or directory: ''
2019-09-03 12:03:16,267 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [__init__ ][__file__:16]- 操作EXCEL表类初始化异常，异常原因：'NoneType' object has no attribute 'nrows'
2019-09-03 12:03:16,267 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_row_col_list ][__file__:129]- 操作EXCEL表类获取值对应的行号出现异常，异常原因：'NoneType' object has no attribute 'nrows'
2019-09-03 12:03:16,267 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：'NoneType' object is not subscriptable
2019-09-03 12:05:34,210 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_sheet ][__file__:34]- 操作EXCEL表类获取sheet页内容异常，异常原因：[Errno 2] No such file or directory: ''
2019-09-03 12:05:34,210 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [__init__ ][__file__:16]- 操作EXCEL表类初始化异常，异常原因：'NoneType' object has no attribute 'nrows'
2019-09-03 12:05:34,211 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_row_col_list ][__file__:129]- 操作EXCEL表类获取值对应的行号出现异常，异常原因：'NoneType' object has no attribute 'nrows'
2019-09-03 12:05:34,211 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：'NoneType' object is not subscriptable
2019-09-03 12:05:34,211 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_sheet ][__file__:34]- 操作EXCEL表类获取sheet页内容异常，异常原因：[Errno 2] No such file or directory: ''
2019-09-03 12:05:34,211 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [__init__ ][__file__:16]- 操作EXCEL表类初始化异常，异常原因：'NoneType' object has no attribute 'nrows'
2019-09-03 12:05:34,211 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_row_col_list ][__file__:129]- 操作EXCEL表类获取值对应的行号出现异常，异常原因：'NoneType' object has no attribute 'nrows'
2019-09-03 12:05:34,211 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：'NoneType' object is not subscriptable
2019-09-03 12:06:29,068 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_sheet ][__file__:34]- 操作EXCEL表类获取sheet页内容异常，异常原因：[Errno 2] No such file or directory: ''
2019-09-03 12:06:29,068 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [__init__ ][__file__:16]- 操作EXCEL表类初始化异常，异常原因：'NoneType' object has no attribute 'nrows'
2019-09-03 12:06:29,068 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_row_col_list ][__file__:129]- 操作EXCEL表类获取值对应的行号出现异常，异常原因：'NoneType' object has no attribute 'nrows'
2019-09-03 12:06:29,069 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：'NoneType' object is not subscriptable
2019-09-03 12:06:29,069 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_sheet ][__file__:34]- 操作EXCEL表类获取sheet页内容异常，异常原因：[Errno 2] No such file or directory: ''
2019-09-03 12:06:29,069 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [__init__ ][__file__:16]- 操作EXCEL表类初始化异常，异常原因：'NoneType' object has no attribute 'nrows'
2019-09-03 12:06:29,069 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_row_col_list ][__file__:129]- 操作EXCEL表类获取值对应的行号出现异常，异常原因：'NoneType' object has no attribute 'nrows'
2019-09-03 12:06:29,069 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：'NoneType' object is not subscriptable
2019-09-03 12:08:04,592 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_sheet ][__file__:34]- 操作EXCEL表类获取sheet页内容异常，异常原因：[Errno 2] No such file or directory: ''
2019-09-03 12:08:04,592 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [__init__ ][__file__:16]- 操作EXCEL表类初始化异常，异常原因：'NoneType' object has no attribute 'nrows'
2019-09-03 12:08:04,592 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_row_col_list ][__file__:129]- 操作EXCEL表类获取值对应的行号出现异常，异常原因：'NoneType' object has no attribute 'nrows'
2019-09-03 12:08:04,592 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：'NoneType' object is not subscriptable
2019-09-03 12:08:04,593 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_sheet ][__file__:34]- 操作EXCEL表类获取sheet页内容异常，异常原因：[Errno 2] No such file or directory: ''
2019-09-03 12:08:04,593 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [__init__ ][__file__:16]- 操作EXCEL表类初始化异常，异常原因：'NoneType' object has no attribute 'nrows'
2019-09-03 12:08:04,593 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_row_col_list ][__file__:129]- 操作EXCEL表类获取值对应的行号出现异常，异常原因：'NoneType' object has no attribute 'nrows'
2019-09-03 12:08:04,593 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：'NoneType' object is not subscriptable
2019-09-03 12:08:33,727 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_sheet ][__file__:34]- 操作EXCEL表类获取sheet页内容异常，异常原因：[Errno 2] No such file or directory: ''
2019-09-03 12:08:33,727 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [__init__ ][__file__:16]- 操作EXCEL表类初始化异常，异常原因：'NoneType' object has no attribute 'nrows'
2019-09-03 12:08:33,727 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_row_col_list ][__file__:129]- 操作EXCEL表类获取值对应的行号出现异常，异常原因：'NoneType' object has no attribute 'nrows'
2019-09-03 12:08:33,727 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：'NoneType' object is not subscriptable
2019-09-03 12:08:33,727 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_sheet ][__file__:34]- 操作EXCEL表类获取sheet页内容异常，异常原因：[Errno 2] No such file or directory: ''
2019-09-03 12:08:33,727 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [__init__ ][__file__:16]- 操作EXCEL表类初始化异常，异常原因：'NoneType' object has no attribute 'nrows'
2019-09-03 12:08:33,727 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_row_col_list ][__file__:129]- 操作EXCEL表类获取值对应的行号出现异常，异常原因：'NoneType' object has no attribute 'nrows'
2019-09-03 12:08:33,727 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：'NoneType' object is not subscriptable
2019-09-03 13:56:33,669 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_sheet ][__file__:34]- 操作EXCEL表类获取sheet页内容异常，异常原因：[Errno 2] No such file or directory: ''
2019-09-03 13:56:33,670 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [__init__ ][__file__:16]- 操作EXCEL表类初始化异常，异常原因：'NoneType' object has no attribute 'nrows'
2019-09-03 13:56:33,670 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_row_col_list ][__file__:129]- 操作EXCEL表类获取值对应的行号出现异常，异常原因：'NoneType' object has no attribute 'nrows'
2019-09-03 13:56:33,670 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：'NoneType' object is not subscriptable
2019-09-03 13:56:33,670 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_sheet ][__file__:34]- 操作EXCEL表类获取sheet页内容异常，异常原因：[Errno 2] No such file or directory: ''
2019-09-03 13:56:33,670 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [__init__ ][__file__:16]- 操作EXCEL表类初始化异常，异常原因：'NoneType' object has no attribute 'nrows'
2019-09-03 13:56:33,670 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_row_col_list ][__file__:129]- 操作EXCEL表类获取值对应的行号出现异常，异常原因：'NoneType' object has no attribute 'nrows'
2019-09-03 13:56:33,670 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：'NoneType' object is not subscriptable
2019-09-03 13:58:14,602 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_sheet ][__file__:34]- 操作EXCEL表类获取sheet页内容异常，异常原因：[Errno 2] No such file or directory: ''
2019-09-03 13:58:14,602 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [__init__ ][__file__:16]- 操作EXCEL表类初始化异常，异常原因：'NoneType' object has no attribute 'nrows'
2019-09-03 13:58:14,602 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_row_col_list ][__file__:129]- 操作EXCEL表类获取值对应的行号出现异常，异常原因：'NoneType' object has no attribute 'nrows'
2019-09-03 13:58:14,603 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：'NoneType' object is not subscriptable
2019-09-03 13:58:14,603 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_sheet ][__file__:34]- 操作EXCEL表类获取sheet页内容异常，异常原因：[Errno 2] No such file or directory: ''
2019-09-03 13:58:14,603 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [__init__ ][__file__:16]- 操作EXCEL表类初始化异常，异常原因：'NoneType' object has no attribute 'nrows'
2019-09-03 13:58:14,603 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_row_col_list ][__file__:129]- 操作EXCEL表类获取值对应的行号出现异常，异常原因：'NoneType' object has no attribute 'nrows'
2019-09-03 13:58:14,603 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：'NoneType' object is not subscriptable
2019-09-03 14:13:26,298 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_sheet ][__file__:34]- 操作EXCEL表类获取sheet页内容异常，异常原因：[Errno 2] No such file or directory: ''
2019-09-03 14:13:26,298 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [__init__ ][__file__:16]- 操作EXCEL表类初始化异常，异常原因：'NoneType' object has no attribute 'nrows'
2019-09-03 14:13:26,298 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_row_col_list ][__file__:129]- 操作EXCEL表类获取值对应的行号出现异常，异常原因：'NoneType' object has no attribute 'nrows'
2019-09-03 14:13:26,298 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：'NoneType' object is not subscriptable
2019-09-03 14:13:26,298 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_sheet ][__file__:34]- 操作EXCEL表类获取sheet页内容异常，异常原因：[Errno 2] No such file or directory: ''
2019-09-03 14:13:26,298 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [__init__ ][__file__:16]- 操作EXCEL表类初始化异常，异常原因：'NoneType' object has no attribute 'nrows'
2019-09-03 14:13:26,298 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_row_col_list ][__file__:129]- 操作EXCEL表类获取值对应的行号出现异常，异常原因：'NoneType' object has no attribute 'nrows'
2019-09-03 14:13:26,299 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：'NoneType' object is not subscriptable
2019-09-03 14:27:40,017 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_sheet ][__file__:34]- 操作EXCEL表类获取sheet页内容异常，异常原因：[Errno 2] No such file or directory: ''
2019-09-03 14:27:40,017 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [__init__ ][__file__:16]- 操作EXCEL表类初始化异常，异常原因：'NoneType' object has no attribute 'nrows'
2019-09-03 14:27:40,018 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_row_col_list ][__file__:129]- 操作EXCEL表类获取值对应的行号出现异常，异常原因：'NoneType' object has no attribute 'nrows'
2019-09-03 14:27:40,018 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：'NoneType' object is not subscriptable
2019-09-03 14:27:40,018 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_sheet ][__file__:34]- 操作EXCEL表类获取sheet页内容异常，异常原因：[Errno 2] No such file or directory: ''
2019-09-03 14:27:40,018 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [__init__ ][__file__:16]- 操作EXCEL表类初始化异常，异常原因：'NoneType' object has no attribute 'nrows'
2019-09-03 14:27:40,018 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_row_col_list ][__file__:129]- 操作EXCEL表类获取值对应的行号出现异常，异常原因：'NoneType' object has no attribute 'nrows'
2019-09-03 14:27:40,018 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：'NoneType' object is not subscriptable
2019-09-03 14:52:22,151 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_sheet ][__file__:34]- 操作EXCEL表类获取sheet页内容异常，异常原因：[Errno 2] No such file or directory: ''
2019-09-03 14:52:22,151 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [__init__ ][__file__:16]- 操作EXCEL表类初始化异常，异常原因：'NoneType' object has no attribute 'nrows'
2019-09-03 14:52:22,151 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_row_col_list ][__file__:129]- 操作EXCEL表类获取值对应的行号出现异常，异常原因：'NoneType' object has no attribute 'nrows'
2019-09-03 14:52:22,151 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：'NoneType' object is not subscriptable
2019-09-03 14:52:22,151 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_sheet ][__file__:34]- 操作EXCEL表类获取sheet页内容异常，异常原因：[Errno 2] No such file or directory: ''
2019-09-03 14:52:22,151 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [__init__ ][__file__:16]- 操作EXCEL表类初始化异常，异常原因：'NoneType' object has no attribute 'nrows'
2019-09-03 14:52:22,151 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_row_col_list ][__file__:129]- 操作EXCEL表类获取值对应的行号出现异常，异常原因：'NoneType' object has no attribute 'nrows'
2019-09-03 14:52:22,151 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：'NoneType' object is not subscriptable
2019-09-03 15:00:51,220 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_sheet ][__file__:34]- 操作EXCEL表类获取sheet页内容异常，异常原因：[Errno 2] No such file or directory: ''
2019-09-03 15:00:51,220 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [__init__ ][__file__:16]- 操作EXCEL表类初始化异常，异常原因：'NoneType' object has no attribute 'nrows'
2019-09-03 15:00:51,220 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_row_col_list ][__file__:129]- 操作EXCEL表类获取值对应的行号出现异常，异常原因：'NoneType' object has no attribute 'nrows'
2019-09-03 15:00:51,220 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：'NoneType' object is not subscriptable
2019-09-03 15:00:51,220 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_sheet ][__file__:34]- 操作EXCEL表类获取sheet页内容异常，异常原因：[Errno 2] No such file or directory: ''
2019-09-03 15:00:51,220 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [__init__ ][__file__:16]- 操作EXCEL表类初始化异常，异常原因：'NoneType' object has no attribute 'nrows'
2019-09-03 15:00:51,220 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_row_col_list ][__file__:129]- 操作EXCEL表类获取值对应的行号出现异常，异常原因：'NoneType' object has no attribute 'nrows'
2019-09-03 15:00:51,220 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：'NoneType' object is not subscriptable
2019-09-03 15:15:48,991 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_sheet ][__file__:34]- 操作EXCEL表类获取sheet页内容异常，异常原因：[Errno 2] No such file or directory: ''
2019-09-03 15:15:48,991 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [__init__ ][__file__:16]- 操作EXCEL表类初始化异常，异常原因：'NoneType' object has no attribute 'nrows'
2019-09-03 15:15:48,991 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_row_col_list ][__file__:129]- 操作EXCEL表类获取值对应的行号出现异常，异常原因：'NoneType' object has no attribute 'nrows'
2019-09-03 15:15:48,991 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：'NoneType' object is not subscriptable
2019-09-03 15:15:48,991 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_sheet ][__file__:34]- 操作EXCEL表类获取sheet页内容异常，异常原因：[Errno 2] No such file or directory: ''
2019-09-03 15:15:48,991 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [__init__ ][__file__:16]- 操作EXCEL表类初始化异常，异常原因：'NoneType' object has no attribute 'nrows'
2019-09-03 15:15:48,991 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_row_col_list ][__file__:129]- 操作EXCEL表类获取值对应的行号出现异常，异常原因：'NoneType' object has no attribute 'nrows'
2019-09-03 15:15:48,991 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：'NoneType' object is not subscriptable
2019-09-03 15:18:18,164 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_sheet ][__file__:34]- 操作EXCEL表类获取sheet页内容异常，异常原因：[Errno 2] No such file or directory: ''
2019-09-03 15:18:18,164 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [__init__ ][__file__:16]- 操作EXCEL表类初始化异常，异常原因：'NoneType' object has no attribute 'nrows'
2019-09-03 15:18:18,164 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_row_col_list ][__file__:129]- 操作EXCEL表类获取值对应的行号出现异常，异常原因：'NoneType' object has no attribute 'nrows'
2019-09-03 15:18:18,164 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：'NoneType' object is not subscriptable
2019-09-03 15:18:18,164 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_sheet ][__file__:34]- 操作EXCEL表类获取sheet页内容异常，异常原因：[Errno 2] No such file or directory: ''
2019-09-03 15:18:18,164 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [__init__ ][__file__:16]- 操作EXCEL表类初始化异常，异常原因：'NoneType' object has no attribute 'nrows'
2019-09-03 15:18:18,164 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_row_col_list ][__file__:129]- 操作EXCEL表类获取值对应的行号出现异常，异常原因：'NoneType' object has no attribute 'nrows'
2019-09-03 15:18:18,164 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：'NoneType' object is not subscriptable
2019-09-03 15:19:40,305 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_sheet ][__file__:34]- 操作EXCEL表类获取sheet页内容异常，异常原因：[Errno 2] No such file or directory: ''
2019-09-03 15:19:40,305 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [__init__ ][__file__:16]- 操作EXCEL表类初始化异常，异常原因：'NoneType' object has no attribute 'nrows'
2019-09-03 15:19:40,305 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_row_col_list ][__file__:129]- 操作EXCEL表类获取值对应的行号出现异常，异常原因：'NoneType' object has no attribute 'nrows'
2019-09-03 15:19:40,306 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：'NoneType' object is not subscriptable
2019-09-03 15:19:40,306 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_sheet ][__file__:34]- 操作EXCEL表类获取sheet页内容异常，异常原因：[Errno 2] No such file or directory: ''
2019-09-03 15:19:40,306 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [__init__ ][__file__:16]- 操作EXCEL表类初始化异常，异常原因：'NoneType' object has no attribute 'nrows'
2019-09-03 15:19:40,306 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_row_col_list ][__file__:129]- 操作EXCEL表类获取值对应的行号出现异常，异常原因：'NoneType' object has no attribute 'nrows'
2019-09-03 15:19:40,306 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：'NoneType' object is not subscriptable
2019-09-03 15:37:36,828 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_sheet ][__file__:34]- 操作EXCEL表类获取sheet页内容异常，异常原因：[Errno 2] No such file or directory: ''
2019-09-03 15:37:36,828 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [__init__ ][__file__:16]- 操作EXCEL表类初始化异常，异常原因：'NoneType' object has no attribute 'nrows'
2019-09-03 15:37:36,828 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_row_col_list ][__file__:129]- 操作EXCEL表类获取值对应的行号出现异常，异常原因：'NoneType' object has no attribute 'nrows'
2019-09-03 15:37:36,828 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：'NoneType' object is not subscriptable
2019-09-03 15:37:36,828 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_sheet ][__file__:34]- 操作EXCEL表类获取sheet页内容异常，异常原因：[Errno 2] No such file or directory: ''
2019-09-03 15:37:36,828 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [__init__ ][__file__:16]- 操作EXCEL表类初始化异常，异常原因：'NoneType' object has no attribute 'nrows'
2019-09-03 15:37:36,828 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_row_col_list ][__file__:129]- 操作EXCEL表类获取值对应的行号出现异常，异常原因：'NoneType' object has no attribute 'nrows'
2019-09-03 15:37:36,828 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：'NoneType' object is not subscriptable
2019-09-03 15:47:31,384 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_sheet ][__file__:34]- 操作EXCEL表类获取sheet页内容异常，异常原因：[Errno 2] No such file or directory: ''
2019-09-03 15:47:31,385 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [__init__ ][__file__:16]- 操作EXCEL表类初始化异常，异常原因：'NoneType' object has no attribute 'nrows'
2019-09-03 15:47:31,385 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_row_col_list ][__file__:129]- 操作EXCEL表类获取值对应的行号出现异常，异常原因：'NoneType' object has no attribute 'nrows'
2019-09-03 15:47:31,385 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：'NoneType' object is not subscriptable
2019-09-03 15:47:31,385 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_sheet ][__file__:34]- 操作EXCEL表类获取sheet页内容异常，异常原因：[Errno 2] No such file or directory: ''
2019-09-03 15:47:31,385 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [__init__ ][__file__:16]- 操作EXCEL表类初始化异常，异常原因：'NoneType' object has no attribute 'nrows'
2019-09-03 15:47:31,385 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_row_col_list ][__file__:129]- 操作EXCEL表类获取值对应的行号出现异常，异常原因：'NoneType' object has no attribute 'nrows'
2019-09-03 15:47:31,385 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：'NoneType' object is not subscriptable
2019-09-03 15:55:33,999 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_sheet ][__file__:34]- 操作EXCEL表类获取sheet页内容异常，异常原因：[Errno 2] No such file or directory: ''
2019-09-03 15:55:33,999 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [__init__ ][__file__:16]- 操作EXCEL表类初始化异常，异常原因：'NoneType' object has no attribute 'nrows'
2019-09-03 15:55:33,999 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_row_col_list ][__file__:129]- 操作EXCEL表类获取值对应的行号出现异常，异常原因：'NoneType' object has no attribute 'nrows'
2019-09-03 15:55:34,000 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：'NoneType' object is not subscriptable
2019-09-03 15:55:34,000 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_sheet ][__file__:34]- 操作EXCEL表类获取sheet页内容异常，异常原因：[Errno 2] No such file or directory: ''
2019-09-03 15:55:34,000 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [__init__ ][__file__:16]- 操作EXCEL表类初始化异常，异常原因：'NoneType' object has no attribute 'nrows'
2019-09-03 15:55:34,000 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_row_col_list ][__file__:129]- 操作EXCEL表类获取值对应的行号出现异常，异常原因：'NoneType' object has no attribute 'nrows'
2019-09-03 15:55:34,000 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：'NoneType' object is not subscriptable
2019-09-03 16:51:59,796 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_cfg.py] [get_section_key_value ][__file__:57]- 读取配置文件段section内容出现异常，异常原因：invalid syntax (<string>, line 1)
2019-09-03 16:52:36,468 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_cfg.py] [get_section_key_value ][__file__:57]- 读取配置文件段section内容出现异常，异常原因：invalid syntax (<string>, line 1)
2019-09-03 16:52:44,706 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_cfg.py] [get_section_key_value ][__file__:57]- 读取配置文件段section内容出现异常，异常原因：invalid syntax (<string>, line 1)
2019-09-03 16:53:38,117 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_sheet ][__file__:34]- 操作EXCEL表类获取sheet页内容异常，异常原因：[Errno 2] No such file or directory: ''
2019-09-03 16:53:38,118 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [__init__ ][__file__:16]- 操作EXCEL表类初始化异常，异常原因：'NoneType' object has no attribute 'nrows'
2019-09-03 16:53:38,118 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_row_col_list ][__file__:129]- 操作EXCEL表类获取值对应的行号出现异常，异常原因：'NoneType' object has no attribute 'nrows'
2019-09-03 16:53:38,118 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：'NoneType' object is not subscriptable
2019-09-03 16:53:38,118 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_sheet ][__file__:34]- 操作EXCEL表类获取sheet页内容异常，异常原因：[Errno 2] No such file or directory: ''
2019-09-03 16:53:38,118 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [__init__ ][__file__:16]- 操作EXCEL表类初始化异常，异常原因：'NoneType' object has no attribute 'nrows'
2019-09-03 16:53:38,118 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_row_col_list ][__file__:129]- 操作EXCEL表类获取值对应的行号出现异常，异常原因：'NoneType' object has no attribute 'nrows'
2019-09-03 16:53:38,118 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：'NoneType' object is not subscriptable
2019-09-03 16:53:39,229 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/common/cmp_res_req.py] [verify_database ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/common/cmp_res_req.py:99]- 测试用例请求参数与存储结果对比出现异常，异常原因：Invalid URL 'None': No schema supplied. Perhaps you meant http://None?
2019-09-03 16:57:14,888 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_sheet ][__file__:34]- 操作EXCEL表类获取sheet页内容异常，异常原因：[Errno 2] No such file or directory: ''
2019-09-03 16:57:14,888 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [__init__ ][__file__:16]- 操作EXCEL表类初始化异常，异常原因：'NoneType' object has no attribute 'nrows'
2019-09-03 16:57:14,888 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_row_col_list ][__file__:129]- 操作EXCEL表类获取值对应的行号出现异常，异常原因：'NoneType' object has no attribute 'nrows'
2019-09-03 16:57:14,888 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：'NoneType' object is not subscriptable
2019-09-03 16:57:14,888 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_sheet ][__file__:34]- 操作EXCEL表类获取sheet页内容异常，异常原因：[Errno 2] No such file or directory: ''
2019-09-03 16:57:14,888 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [__init__ ][__file__:16]- 操作EXCEL表类初始化异常，异常原因：'NoneType' object has no attribute 'nrows'
2019-09-03 16:57:14,888 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_row_col_list ][__file__:129]- 操作EXCEL表类获取值对应的行号出现异常，异常原因：'NoneType' object has no attribute 'nrows'
2019-09-03 16:57:14,889 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：'NoneType' object is not subscriptable
2019-09-03 16:57:15,968 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/common/cmp_res_req.py] [verify_database ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/common/cmp_res_req.py:99]- 测试用例请求参数与存储结果对比出现异常，异常原因：Invalid URL 'None': No schema supplied. Perhaps you meant http://None?
2019-09-03 17:10:55,280 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_sheet ][__file__:34]- 操作EXCEL表类获取sheet页内容异常，异常原因：[Errno 2] No such file or directory: ''
2019-09-03 17:10:55,281 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [__init__ ][__file__:16]- 操作EXCEL表类初始化异常，异常原因：'NoneType' object has no attribute 'nrows'
2019-09-03 17:10:55,281 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_row_col_list ][__file__:129]- 操作EXCEL表类获取值对应的行号出现异常，异常原因：'NoneType' object has no attribute 'nrows'
2019-09-03 17:10:55,281 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：'NoneType' object is not subscriptable
2019-09-03 17:10:55,281 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_sheet ][__file__:34]- 操作EXCEL表类获取sheet页内容异常，异常原因：[Errno 2] No such file or directory: ''
2019-09-03 17:10:55,281 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [__init__ ][__file__:16]- 操作EXCEL表类初始化异常，异常原因：'NoneType' object has no attribute 'nrows'
2019-09-03 17:10:55,282 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_row_col_list ][__file__:129]- 操作EXCEL表类获取值对应的行号出现异常，异常原因：'NoneType' object has no attribute 'nrows'
2019-09-03 17:10:55,282 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：'NoneType' object is not subscriptable
2019-09-03 17:11:47,125 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_sheet ][__file__:34]- 操作EXCEL表类获取sheet页内容异常，异常原因：[Errno 2] No such file or directory: ''
2019-09-03 17:11:47,125 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [__init__ ][__file__:16]- 操作EXCEL表类初始化异常，异常原因：'NoneType' object has no attribute 'nrows'
2019-09-03 17:11:47,125 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_row_col_list ][__file__:129]- 操作EXCEL表类获取值对应的行号出现异常，异常原因：'NoneType' object has no attribute 'nrows'
2019-09-03 17:11:47,125 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：'NoneType' object is not subscriptable
2019-09-03 17:11:47,125 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_sheet ][__file__:34]- 操作EXCEL表类获取sheet页内容异常，异常原因：[Errno 2] No such file or directory: ''
2019-09-03 17:11:47,126 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [__init__ ][__file__:16]- 操作EXCEL表类初始化异常，异常原因：'NoneType' object has no attribute 'nrows'
2019-09-03 17:11:47,126 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_row_col_list ][__file__:129]- 操作EXCEL表类获取值对应的行号出现异常，异常原因：'NoneType' object has no attribute 'nrows'
2019-09-03 17:11:47,126 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：'NoneType' object is not subscriptable
2019-09-03 17:57:02,409 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_sheet ][__file__:34]- 操作EXCEL表类获取sheet页内容异常，异常原因：[Errno 2] No such file or directory: ''
2019-09-03 17:57:02,409 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [__init__ ][__file__:16]- 操作EXCEL表类初始化异常，异常原因：'NoneType' object has no attribute 'nrows'
2019-09-03 17:57:02,409 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_row_col_list ][__file__:129]- 操作EXCEL表类获取值对应的行号出现异常，异常原因：'NoneType' object has no attribute 'nrows'
2019-09-03 17:57:02,409 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：'NoneType' object is not subscriptable
2019-09-03 17:57:02,410 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_sheet ][__file__:34]- 操作EXCEL表类获取sheet页内容异常，异常原因：[Errno 2] No such file or directory: ''
2019-09-03 17:57:02,410 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [__init__ ][__file__:16]- 操作EXCEL表类初始化异常，异常原因：'NoneType' object has no attribute 'nrows'
2019-09-03 17:57:02,410 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_row_col_list ][__file__:129]- 操作EXCEL表类获取值对应的行号出现异常，异常原因：'NoneType' object has no attribute 'nrows'
2019-09-03 17:57:02,410 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：'NoneType' object is not subscriptable
2019-09-03 17:57:03,984 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/common/cmp_res_req.py] [verify_database ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/common/cmp_res_req.py:99]- 测试用例请求参数与存储结果对比出现异常，异常原因：Invalid URL 'None': No schema supplied. Perhaps you meant http://None?
2019-09-03 18:00:45,173 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_sheet ][__file__:34]- 操作EXCEL表类获取sheet页内容异常，异常原因：[Errno 2] No such file or directory: ''
2019-09-03 18:00:45,173 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [__init__ ][__file__:16]- 操作EXCEL表类初始化异常，异常原因：'NoneType' object has no attribute 'nrows'
2019-09-03 18:00:45,173 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_row_col_list ][__file__:129]- 操作EXCEL表类获取值对应的行号出现异常，异常原因：'NoneType' object has no attribute 'nrows'
2019-09-03 18:00:45,173 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：'NoneType' object is not subscriptable
2019-09-03 18:00:45,173 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_sheet ][__file__:34]- 操作EXCEL表类获取sheet页内容异常，异常原因：[Errno 2] No such file or directory: ''
2019-09-03 18:00:45,173 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [__init__ ][__file__:16]- 操作EXCEL表类初始化异常，异常原因：'NoneType' object has no attribute 'nrows'
2019-09-03 18:00:45,173 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/utils/operation_excel.py] [get_row_col_list ][__file__:129]- 操作EXCEL表类获取值对应的行号出现异常，异常原因：'NoneType' object has no attribute 'nrows'
2019-09-03 18:00:45,173 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py] [__init__ ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/get_data/tsa_param_dic.py:34]- 接口参数处理类初始化异常，异常原因：'NoneType' object is not subscriptable
2019-09-03 18:00:46,253 [ERROR] [/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/common/cmp_res_req.py] [verify_database ][/home/ma/PycharmProjects/AutoTest_python/InterfaceTest/python_excel/common/cmp_res_req.py:99]- 测试用例请求参数与存储结果对比出现异常，异常原因：Invalid URL 'None': No schema supplied. Perhaps you meant http://None?
